version: '3.8'

services:
  power-usage-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map container port 5000 to host port 5000
    volumes:
      - ./power_usage.py:/app/power_usage.py:ro  # Mount your script read-only
    restart: unless-stopped
